### ISSUE TITLE
Lightline support

### ISSUE THREAD

**Issue by lucat1** [co1ncidence/monokai-pro.vim#3]
Amazing work on the theme, finally a good port for vim.
I've noticed you provided support for lightline in some of your other themes and was wondering if you could implement it here.

**Comment by co1ncidence** [comment]
Sorry for the extremely late response to this issue @lucat1 .

This theme was actually made as a bit of a joke between me and some friends, and I wasn't planning on maintaining it or actually taking it seriously lmao, but since it has gotten some stars I will probably give it an update sometime soon. 

As for the lightline theme, I don't actually use lightline myself so making those themes is a bit of a pain, if you could make a `pr` for one that you have made, I would gladly accept it (and fix it if I need to)

Once again sorry for the late reply.

**Comment by lucat1** [comment]
I am fine with making a PR whenever you prefer but I'm uncertain as to which colours should be used. My fork currently uses colours that I find pleasing, but that's entirely subjective and I can't find a reference implementation to base my configuration off of.

**Comment by co1ncidence** [comment]
For colors, here is the palette I recommend.

Bases:
  - Black (for background/middle line of lightline): `#2b292e`
  - Gray (for the lighter background of other elements): `#3d3b40`
  - Lighter Gray (your choice if you want to use this): `#575558`
  - White (for a foreground color): `#fdf9f3`

Main Colors, you can set any of these for any mode, there aren't really any restrictions. i.e. you could have red for insert and purple for visual mode:
  - Red:     `#FF6188`
  - Orange:  `#FC9867`
  - Yellow:  `#FFD866`
  - Green:   `#A9DC76`
  - Cyan:    `#78DCE8`
  - Blue:    `#AB9DF2`
  - Magenta: `#DC9DF2`

My recommendation is that you set the large (empty) middle section of light line to be the black color (so it blends in) and then set the background of elements on the left and right to the darker gray, with only the foreground color changing when you switch between modes.
